language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN=e00e89f8-5303-4314-a051-02e785ea6926

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - asultangareev@gmail.com
    on_success: never # default: change
    on_failure: always # default: always